name: Build Windows Executable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Download Go modules
      run: |
        go mod download
        go mod tidy
    
    - name: Build Windows executables
      run: |
        mkdir -p dist
        # Build sample app
        GOOS=windows GOARCH=amd64 go build -o dist/app-windows-amd64.exe ./cmd/main.go
        GOOS=windows GOARCH=386 go build -o dist/app-windows-386.exe ./cmd/main.go
        # Build Claude Desktop config tool
        GOOS=windows GOARCH=amd64 go build -ldflags="-H windowsgui" -o dist/claude-config-windows-amd64.exe ./cmd/claude-config/main.go
        GOOS=windows GOARCH=386 go build -ldflags="-H windowsgui" -o dist/claude-config-windows-386.exe ./cmd/claude-config/main.go
    
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        artifacts: |
          dist/app-windows-amd64.exe
          dist/app-windows-386.exe
          dist/claude-config-windows-amd64.exe
          dist/claude-config-windows-386.exe
        body: |
          ## Downloads
          - **claude-config-windows-amd64.exe** - Claude Desktop MCP Configuration Tool (64-bit)
          - **claude-config-windows-386.exe** - Claude Desktop MCP Configuration Tool (32-bit)
          - **app-windows-amd64.exe** - Sample Application (64-bit)
          - **app-windows-386.exe** - Sample Application (32-bit)
          
          ### Usage
          Download and run `claude-config-windows-amd64.exe` to configure Claude Desktop MCP servers.
        token: ${{ secrets.GITHUB_TOKEN }}