name: Build Windows Executable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Download Go modules
      run: |
        go mod download
        go mod tidy
    
    - name: Build Windows executables
      run: |
        mkdir -p dist
        # Build sample app (64-bit only)
        GOOS=windows GOARCH=amd64 go build -o dist/app-windows-amd64.exe ./cmd/main.go
        # Build Claude Desktop config tool (64-bit only) - console app
        GOOS=windows GOARCH=amd64 go build -o dist/claude-config-windows-amd64.exe ./cmd/claude-config/main.go
    
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        artifacts: |
          dist/app-windows-amd64.exe
          dist/claude-config-windows-amd64.exe
        body: |
          ## Downloads
          - **claude-config-windows-amd64.exe** - Claude Desktop MCP Configuration Tool (Console-based, 64-bit Windows)
          - **app-windows-amd64.exe** - Sample Application (64-bit Windows)
          
          ### Usage
          Download and run `claude-config-windows-amd64.exe` in Command Prompt or PowerShell to configure Claude Desktop MCP servers.
          
          The configuration tool provides an interactive console interface to enable/disable RPLS and Queenit MCP servers.
          
          **System Requirements:** 64-bit Windows (Windows 7 or later)
        token: ${{ secrets.GITHUB_TOKEN }}